### ISSUE TITLE
Problem On step installation step 12

### ISSUE THREAD

**Issue by rupokdas147** [bmurmann/EE628#58]
After completing step 12, I saw a menu item saying "SG13G2 PDK". But I did not find anything named "Load PDK options". Moreover, after this step "LIB - sg13g2_pr.gds" has vanished from my library options, remaining only "LIB - sg1352_sdcells.gds". There are some errors in the terminal though.
![image](https://github.com/user-attachments/assets/8cccaa9d-b0f4-4a1f-b44e-82d71dd768ee)

**Comment by bmurmann** [comment]
These instructions were created for the PDK's beta version as of January-March 2023 (and will not be updated until next year). There will be discrepancies when you work with the latest PDK version and you will need to resolve on your own.
